const ACTION_TYPES = {
    //Counter
    INCREMENT_COUNT :'INCREMENT_COUNT',
    DECREMENT_COUNT :'DECREMENT_COUNT',
    SET_STEP :'SET_STEP',
    //ToDoList
    CREATE_TASK: 'CREATE_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    DELETE_TASK: 'DELETE_TASK'
}
export default ACTION_TYPES